from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path
from typing import Any

import numpy as np
import pydicom
import torch
import uvicorn
from fastapi import FastAPI, File, UploadFile
from PIL import Image

from radiology_trainer.xraydar_labels import (
    XRAYDAR_LABELS,
    display_xraydar_label,
    normalize_xraydar_label,
)


def main() -> None:
    args = _parse_args()
    service = XRaydarService(args.backend_dir, args.device)
    app = _create_app(service)
    uvicorn.run(app, host=args.host, port=args.port)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run X-Raydar as an HTTP evidence service.")
    parser.add_argument("--backend-dir", type=Path, default=Path("outputs/xraydar-cv"))
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=9000)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    return parser.parse_args()


class XRaydarService:
    def __init__(self, backend_dir: Path, device: str) -> None:
        self.backend_dir = backend_dir.resolve()
        self.src_dir = self.backend_dir / "src"
        self.device = torch.device(device)
        if str(self.src_dir) not in sys.path:
            sys.path.insert(0, str(self.src_dir))
        _patch_upstream_compatibility()

        import model_20210820_XNet38MS.XNet38_urg as xnet
        import model_20210820_XNet38MS.predict as predict
        import utils.dicom_utils as dicom_utils

        self.xnet = xnet
        self.predict = predict
        self.dicom_utils = dicom_utils
        self.models = self._build_models()

    def analyze_file(self, path: Path) -> dict[str, Any]:
        image = self._load_image(path)
        probs, urgency = self._predict_probs(image)
        findings = [
            {
                "label": display_xraydar_label(label),
                "raw_label": normalize_xraydar_label(label),
                "score": float(score),
                "source": "xraydar-cv",
                "explanation": "X-Raydar CV probability from local model service.",
            }
            for label, score in zip(XRAYDAR_LABELS, probs, strict=True)
        ]
        findings.sort(key=lambda item: item["score"], reverse=True)
        return {
            "anatomy": "chest",
            "findings": findings,
            "regions": [],
            "agreement_notes": [f"X-Raydar urgency estimate: {urgency}"],
            "model_notes": [
                "Evidence generated by local X-Raydar CV backend.",
                f"Device: {self.device.type}",
            ],
        }

    def _build_models(self) -> dict[int, torch.nn.Module]:
        models = {}
        for size in [299, 512, 1024]:
            weight_dir = (
                self.src_dir
                / "model_20210820_XNet38MS"
                / "model_weights"
                / f"direct_multi93_is{size}_Rv10_pre00_imagenet"
            )
            if not (weight_dir / "model_best.pth.tar").exists():
                raise FileNotFoundError(
                    f"Missing X-Raydar weights for {size}px. "
                    "Run `uv run python scripts/download_xraydar_backend.py`."
                )
            model = self.xnet.XNet38_urg()
            model.load_state_dict(str(weight_dir))
            model.to(self.device)
            model.eval()
            models[size] = model
        return models

    def _predict_probs(self, image: np.ndarray) -> tuple[np.ndarray, str]:
        dict_images = self.predict.prepare_data(image)
        probs_multi = []
        urgency_probs = []

        with torch.no_grad():
            for size, tensor in dict_images.items():
                logits_multi, logits_urg = self.models[size](tensor.to(self.device))
                probs_multi.append(logits_multi[0].detach().cpu().sigmoid())
                urgency_probs.append(logits_urg[0].detach().cpu().softmax(0))

        probs = torch.stack(probs_multi, 0).mean(0).numpy().ravel()
        urgencies = np.array(
            [1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 2, 3, 1, 2, 2, 2, 2, 2, 3, 3, 3, 2, 2, 1, 3, 1, 2, 1]
        )
        urgency_text = ["normal", "non-urgent", "urgent", "critical"]
        urgency = urgency_text[int(np.max((probs > 0.5) * urgencies))]
        return probs, urgency

    def _load_image(self, path: Path) -> np.ndarray:
        suffix = path.suffix.lower()
        if suffix in {".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff", ".webp"}:
            with Image.open(path) as image:
                return np.asarray(image.convert("L")).astype(np.uint8)
        return self.dicom_utils.img_clean(str(path)).astype(np.uint8)


def _create_app(service: XRaydarService) -> FastAPI:
    app = FastAPI(title="X-Raydar Evidence Service")

    @app.get("/health")
    def health() -> dict[str, Any]:
        return {
            "status": "ok",
            "backend": "xraydar-cv",
            "device": service.device.type,
        }

    @app.post("/analyze")
    async def analyze(image: UploadFile = File(...)) -> dict[str, Any]:
        suffix = Path(image.filename or "upload").suffix
        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
            tmp.write(await image.read())
            tmp_path = Path(tmp.name)
        try:
            return service.analyze_file(tmp_path)
        finally:
            try:
                os.unlink(tmp_path)
            except FileNotFoundError:
                pass

    return app


def _patch_upstream_compatibility() -> None:
    # X-Raydar checkpoints are official HF-hosted files, but their upstream loader
    # predates PyTorch's weights_only=True default.
    original_torch_load = torch.load

    def trusted_torch_load(*args, **kwargs):
        kwargs.setdefault("weights_only", False)
        return original_torch_load(*args, **kwargs)

    torch.load = trusted_torch_load
    if not hasattr(pydicom, "read_file"):
        pydicom.read_file = pydicom.dcmread


if __name__ == "__main__":
    main()
